### ==========================================
## ZATCH REEL RECOMMENDATION ENGINE
## NOTEBOOK 01 : DATA PREPROCESSING
### ==========================================

## Importing important Libraries

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import ast
import json
import re

from datetime import datetime

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

print("Libraries Loaded Successfully")

Libraries Loaded Successfully

In [2]:
# DATA PATHS

DATA_PATH = r"E:\zatch-reel-recommendation\data"

BITS_PATH = f"{DATA_PATH}\\bits.csv"
PRODUCTS_PATH = f"{DATA_PATH}\\products.csv"
USERS_PATH = f"{DATA_PATH}\\users.csv"
REELVIEWS_PATH = f"{DATA_PATH}\\reelviews.csv"

print("Paths Configured")

Paths Configured

## Loding Datasets

In [3]:
bits_df = pd.read_csv(BITS_PATH)
products_df = pd.read_csv(PRODUCTS_PATH)
users_df = pd.read_csv(USERS_PATH)
reelviews_df = pd.read_csv(REELVIEWS_PATH)

print("Datasets Loaded")

Datasets Loaded

In [4]:
# Dataset Shapes
print("Bits Shape:", bits_df.shape)
print("Products Shape:", products_df.shape)
print("Users Shape:", users_df.shape)
print("ReelViews Shape:", reelviews_df.shape)

Bits Shape: (87, 20)
Products Shape: (106, 38)
Users Shape: (141, 34)
ReelViews Shape: (1659, 20)

In [5]:
# Verify columns 

datasets = {
    "BITS": bits_df,
    "PRODUCTS": products_df,
    "USERS": users_df,
    "REELVIEWS": reelviews_df
}

for name, df in datasets.items():
    print("\n")
    print("=" * 60)
    print(name)
    print("=" * 60)
    print(df.columns.tolist())

============================================================
BITS
============================================================
['_id', 'title', 'description', 'video', 'thumbnail', 'hashtags', 'products', 'userId', 'likes', 'likeCount', 'shareLink', 'viewCount', 'shareCount', 'revenue', 'orders', 'isActive', 'comments', 'createdAt', '__v', 'isTrending']


============================================================
PRODUCTS
============================================================
['_id', 'sellerId', 'shareCount', 'totalStock', 'categoryType', 'productType', 'stepData', 'orderAcceptingType', 'shipping', 'isSold', 'soldAt', 'isTopPick', 'topPickExpiresAt', 'saveCount', 'likeCount', 'viewCount', 'status', 'bargainSettings', 'tags', 'searchKeywords', 'condition', 'analytics', 'images', 'variants', 'comments', 'customSpecs', 'name', 'description', 'price', 'discountedPrice', 'category', 'subCategory', 'createdAt', 'updatedAt', 'SKU', '__v', 'productCategory', 'hsn']


============================================================
USERS
============================================================
['_id', 'username', 'password', 'countryCode', 'phone', 'email', 'profilePic', 'gender', 'categoryType', 'sellerProfile', 'sellerStatus', 'globalBargainSettings', 'shoppingPreferences', 'followers', 'following', 'followerCount', 'reviewsCount', 'productsSoldCount', 'customerRating', 'savedBits', 'savedProducts', 'likedProducts', 'isAdmin', 'createdAt', 'searchHistory', '__v', 'dob', 'role', 'refreshToken', 'refreshTokenExpiry', 'phoneOtp', 'phoneOtpExpiry', 'emailOtp', 'emailOtpExpiry']


============================================================
REELVIEWS
============================================================
['_id', 'userId', 'bitId', 'watchedMs', 'totalDurationMs', 'watchPercent', 'completedWatch', 'rewatched', 'replayCount', 'pauseCount', 'soundOn', 'tappedProduct', 'scrolledToProduct', 'addedToCart', 'likedDuringWatch', 'sharedDuringWatch', 'source', 'deviceType', 'timestamp', '__v']

In [6]:
# DATASET OVERVIEW

for name, df in datasets.items():

    print("\n")
    print("=" * 80)
    print(name)
    print("=" * 80)

    display(df.info())

================================================================================
BITS
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 87 entries, 0 to 86
Data columns (total 20 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   _id          87 non-null     object
 1   title        87 non-null     object
 2   description  82 non-null     object
 3   video        87 non-null     object
 4   thumbnail    87 non-null     object
 5   hashtags     87 non-null     object
 6   products     87 non-null     object
 7   userId       87 non-null     object
 8   likes        87 non-null     object
 9   likeCount    87 non-null     int64
 10  shareLink    87 non-null     object
 11  viewCount    87 non-null     int64
 12  shareCount   87 non-null     int64
 13  revenue      87 non-null     int64
 14  orders       87 non-null     int64
 15  isActive     87 non-null     bool
 16  comments     87 non-null     object
 17  createdAt    87 non-null     object
 18  __v          87 non-null     int64
 19  isTrending   87 non-null     bool
dtypes: bool(2), int64(6), object(12)
memory usage: 12.5+ KB

None

================================================================================
PRODUCTS
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 106 entries, 0 to 105
Data columns (total 38 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   _id                 106 non-null    object
 1   sellerId            106 non-null    object
 2   shareCount          106 non-null    int64
 3   totalStock          106 non-null    int64
 4   categoryType        106 non-null    object
 5   productType         106 non-null    object
 6   stepData            106 non-null    object
 7   orderAcceptingType  106 non-null    object
 8   shipping            106 non-null    object
 9   isSold              106 non-null    bool
 10  soldAt              0 non-null      float64
 11  isTopPick           106 non-null    bool
 12  topPickExpiresAt    0 non-null      float64
 13  saveCount           106 non-null    int64
 14  likeCount           106 non-null    int64
 15  viewCount           106 non-null    int64
 16  status              106 non-null    object
 17  bargainSettings     106 non-null    object
 18  tags                106 non-null    object
 19  searchKeywords      106 non-null    object
 20  condition           106 non-null    object
 21  analytics           106 non-null    object
 22  images              106 non-null    object
 23  variants            106 non-null    object
 24  comments            106 non-null    object
 25  customSpecs         106 non-null    object
 26  name                106 non-null    object
 27  description         106 non-null    object
 28  price               106 non-null    int64
 29  discountedPrice     106 non-null    int64
 30  category            106 non-null    object
 31  subCategory         106 non-null    object
 32  createdAt           106 non-null    object
 33  updatedAt           106 non-null    object
 34  SKU                 106 non-null    object
 35  __v                 106 non-null    int64
 36  productCategory     4 non-null      object
 37  hsn                 21 non-null     float64
dtypes: bool(2), float64(3), int64(8), object(25)
memory usage: 30.1+ KB

None

================================================================================
USERS
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 141 entries, 0 to 140
Data columns (total 34 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   _id                    141 non-null    object
 1   username               141 non-null    object
 2   password               141 non-null    object
 3   countryCode            141 non-null    int64
 4   phone                  141 non-null    int64
 5   email                  141 non-null    object
 6   profilePic             141 non-null    object
 7   gender                 141 non-null    object
 8   categoryType           141 non-null    object
 9   sellerProfile          141 non-null    object
 10  sellerStatus           141 non-null    object
 11  globalBargainSettings  141 non-null    object
 12  shoppingPreferences    141 non-null    object
 13  followers              141 non-null    object
 14  following              141 non-null    object
 15  followerCount          141 non-null    int64
 16  reviewsCount           141 non-null    int64
 17  productsSoldCount      141 non-null    int64
 18  customerRating         141 non-null    int64
 19  savedBits              141 non-null    object
 20  savedProducts          141 non-null    object
 21  likedProducts          141 non-null    object
 22  isAdmin                141 non-null    bool
 23  createdAt              141 non-null    object
 24  searchHistory          141 non-null    object
 25  __v                    141 non-null    int64
 26  dob                    14 non-null     object
 27  role                   141 non-null    object
 28  refreshToken           93 non-null     object
 29  refreshTokenExpiry     93 non-null     object
 30  phoneOtp               2 non-null      float64
 31  phoneOtpExpiry         2 non-null      object
 32  emailOtp               1 non-null      float64
 33  emailOtpExpiry         1 non-null      object
dtypes: bool(1), float64(2), int64(7), object(24)
memory usage: 36.6+ KB

None

================================================================================
REELVIEWS
================================================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1659 entries, 0 to 1658
Data columns (total 20 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   _id                1659 non-null   object
 1   userId             1659 non-null   object
 2   bitId              1659 non-null   object
 3   watchedMs          1659 non-null   int64
 4   totalDurationMs    1659 non-null   int64
 5   watchPercent       1659 non-null   int64
 6   completedWatch     1659 non-null   bool
 7   rewatched          1659 non-null   bool
 8   replayCount        1659 non-null   int64
 9   pauseCount         1659 non-null   int64
 10  soundOn            1659 non-null   bool
 11  tappedProduct      1648 non-null   object
 12  scrolledToProduct  1659 non-null   bool
 13  addedToCart        1659 non-null   bool
 14  likedDuringWatch   1659 non-null   bool
 15  sharedDuringWatch  1659 non-null   bool
 16  source             1659 non-null   object
 17  deviceType         1659 non-null   object
 18  timestamp          1659 non-null   object
 19  __v                1659 non-null   int64
dtypes: bool(7), int64(6), object(7)
memory usage: 180.0+ KB

None

In [7]:
# SAMPLE RECORDS

display(bits_df.head(3))
display(products_df.head(3))
display(users_df.head(3))
display(reelviews_df.head(3))

,_id,title,description,video,thumbnail,hashtags,products,userId,likes,likeCount,shareLink,viewCount,shareCount,revenue,orders,isActive,comments,createdAt,__v,isTrending
0,{'$oid': '698e30532c63bfbc04769c5e'},Italian pants,Italian pants,"{'public_id': 'zatch/Bits/1770926159931-840210559-1000346333.mp4', 'url': 'https://zatchP.b-cdn.net/zatch/Bits/1770926159931-840210559-1000346333.mp4'}","{'public_id': 'zatch/Bits/thumbnails/1770926163243-530058551-video_thumb.png', 'url': 'https://zatchP.b-cdn.net/zatch/Bits/thumbnails/1770926163243-530058551-video_thumb.png'}","['#pants', '#italian', '#style']",[{'$oid': '698e2fc02c63bfbc047698b2'}],{'$oid': '698e25132c63bfbc047683d8'},"[{'$oid': '698e259d2c63bfbc04768479'}, {'$oid': '698e25132c63bfbc047683d8'}]",2,/bits/1770926163694-698e25132c63bfbc047683d8,54,1,0,0,False,"[{'userId': {'$oid': '698e25132c63bfbc047683d8'}, 'text': 'ygbhi', '_id': {'$oid': '69b8492cd5ba7b8d34deeef7'}, 'createdAt': {'$date': '2026-03-16T18:17:16.392Z'}}]",{'$date': '2026-02-12T19:56:03.694Z'},3,True
1,{'$oid': '698e32a92c63bfbc0476ab3b'},Turtleneck shirts,NaN,"{'public_id': 'zatch/Bits/1770926758467-327345548-1000346301.mp4', 'url': 'https://zatchP.b-cdn.net/zatch/Bits/1770926758467-327345548-1000346301.mp4'}","{'public_id': 'zatch/Bits/thumbnails/1770926761058-859479363-video_thumb.png', 'url': 'https://zatchP.b-cdn.net/zatch/Bits/thumbnails/1770926761058-859479363-video_thumb.png'}","['#turtleneck', '#fashion', '#men']",[{'$oid': '698e32212c63bfbc0476a7f2'}],{'$oid': '698e25132c63bfbc047683d8'},"[{'$oid': '698e259d2c63bfbc04768479'}, {'$oid': '698e6cbe2c63bfbc0476bfa7'}, {'$oid': '699db7d01efc346e038a285b'}]",3,/bits/1770926761537-698e25132c63bfbc047683d8,78,0,0,0,False,[],{'$date': '2026-02-12T20:06:01.538Z'},3,True
2,{'$oid': '698e33892c63bfbc0476b11f'},Leather jacket,NaN,"{'public_id': 'zatch/Bits/1773061731962-97819810-edit_video.mp4', 'url': 'https://zatchP.b-cdn.net/zatch/Bits/1773061731962-97819810-edit_video.mp4'}","{'public_id': 'zatch/Bits/thumbnails/1773061734607-585736512-edit_thumb.png', 'url': 'https://zatchP.b-cdn.net/zatch/Bits/thumbnails/1773061734607-585736512-edit_thumb.png'}","['#jacket', '#fashion', '#style']",[{'$oid': '698e33212c63bfbc0476ae08'}],{'$oid': '698e25132c63bfbc047683d8'},"[{'$oid': '698e259d2c63bfbc04768479'}, {'$oid': '698e6cbe2c63bfbc0476bfa7'}, {'$oid': '69a001c31efc346e038a8bfc'}]",3,/bits/1770926985068-698e25132c63bfbc047683d8,87,0,0,0,False,[],{'$date': '2026-02-12T20:09:45.068Z'},5,True

,_id,sellerId,shareCount,totalStock,categoryType,productType,stepData,orderAcceptingType,shipping,isSold,soldAt,isTopPick,topPickExpiresAt,saveCount,likeCount,viewCount,status,bargainSettings,tags,searchKeywords,condition,analytics,images,variants,comments,customSpecs,name,description,price,discountedPrice,category,subCategory,createdAt,updatedAt,SKU,__v,productCategory,hsn
0,{'$oid': '698e2fc02c63bfbc047698b2'},{'$oid': '698e25132c63bfbc047683d8'},0,25,Products,"{'hasSize': True, 'hasColor': True, 'hasVariants': True}","{'step1': {'bargainSettings': {'autoAcceptDiscount': 5, 'maximumDiscount': 20.602290459206465}, 'category': 'Men', 'subCategory': 'jeans-trousers', 'name': 'Italian pants', 'description': 'Italian pants', 'price': 800, 'discountedPrice': 400, 'totalStock': 25, 'hasSize': True, 'hasColor': True}, 'step2': {'colors': ['grey']}, 'step3': {'images': [{'public_id': 'zatch/products/1770926047349-598994599.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926047349-598994599.jpg', '_id': {'$oid': '698e2fe12c63bfbc04769913'}}, {'public_id': 'zatch/products/1770926048243-263170078.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926048243-263170078.jpg', '_id': {'$oid': '698e2fe12c63bfbc04769914'}}, {'public_id': 'zatch/products/1770926048853-124221894.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926048853-124221894.jpg', '_id': {'$oid': '698e2fe12c63bfbc04769915'}}], 'sizes': ['32'], 'variantImages': {'grey': {'32': [{'public_id': 'zatch/products/variants/1770926049092-833479588.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926049092-833479588.jpg'}, {'public_id': 'zatch/products/variants/1770926049349-861911188.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926049349-861911188.jpg'}, {'public_id': 'zatch/products/variants/1770926049595-91941967.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926049595-91941967.jpg'}]}}}}",autoAccept,"{'freeShipping': False, 'estimatedDeliveryDays': 7, 'codAvailable': False, 'returnPolicy': '7 days return policy'}",False,NaN,False,NaN,0,0,40,inactive,"{'autoAcceptDiscount': 5, 'maximumDiscount': 30}",[],[],New,"{'totalSales': 0, 'totalRevenue': 0, 'averageRating': 0, 'totalReviews': 0}","[{'public_id': 'zatch/products/1770926047349-598994599.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926047349-598994599.jpg', '_id': {'$oid': '698e2fe12c63bfbc04769916'}}, {'public_id': 'zatch/products/1770926048243-263170078.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926048243-263170078.jpg', '_id': {'$oid': '698e2fe12c63bfbc04769917'}}, {'public_id': 'zatch/products/1770926048853-124221894.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926048853-124221894.jpg', '_id': {'$oid': '698e2fe12c63bfbc04769918'}}]","[{'color': 'grey', 'size': '32', 'stock': 23, 'isOutOfStock': False, 'images': [{'public_id': 'zatch/products/variants/1770926049092-833479588.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926049092-833479588.jpg', '_id': {'$oid': '698e2fe62c63bfbc04769922'}}, {'public_id': 'zatch/products/variants/1770926049349-861911188.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926049349-861911188.jpg', '_id': {'$oid': '698e2fe62c63bfbc04769923'}}, {'public_id': 'zatch/products/variants/1770926049595-91941967.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926049595-91941967.jpg', '_id': {'$oid': '698e2fe62c63bfbc04769924'}}]}]",[],[],Italian pants,Italian pants,800,400,Men,jeans-trousers,{'$date': '2026-02-12T19:53:36.12Z'},{'$date': '2026-05-30T17:22:02.953Z'},GEN-698E2F,2,NaN,NaN
1,{'$oid': '698e32212c63bfbc0476a7f2'},{'$oid': '698e25132c63bfbc047683d8'},0,25,Products,"{'hasSize': True, 'hasColor': True, 'hasVariants': True}","{'step1': {'bargainSettings': {'autoAcceptDiscount': 5, 'maximumDiscount': 15.376077426066301}, 'category': 'Men', 'subCategory': 'tshirts-polos', 'name': 'Turtleneck shirts', 'description': 'Turtleneck shirts ', 'price': 999, 'discountedPrice': 899, 'totalStock': 25, 'hasSize': True, 'hasColor': True}, 'step2': {'colors': ['brown']}, 'step3': {'images': [{'public_id': 'zatch/products/1770926647137-88663491.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926647137-88663491.jpg', '_id': {'$oid': '698e323a2c63bfbc0476a8b4'}}, {'public_id': 'zatch/products/1770926648199-146079028.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926648199-146079028.jpg', '_id': {'$oid': '698e323a2c63bfbc0476a8b5'}}, {'public_id': 'zatch/products/1770926648490-777930851.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926648490-777930851.jpg', '_id': {'$oid': '698e323a2c63bfbc0476a8b6'}}], 'sizes': ['MEDIUM'], 'variantImages': {'brown': {'MEDIUM': [{'public_id': 'zatch/products/variants/1770926648909-745129509.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926648909-745129509.jpg'}, {'public_id': 'zatch/products/variants/1770926649174-709929561.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926649174-709929561.jpg'}, {'public_id': 'zatch/products/variants/1770926649461-616656970.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926649461-616656970.jpg'}]}}}}",autoAccept,"{'freeShipping': False, 'estimatedDeliveryDays': 7, 'codAvailable': False, 'returnPolicy': '7 days return policy'}",False,NaN,False,NaN,0,1,43,inactive,"{'autoAcceptDiscount': 5, 'maximumDiscount': 30}",[],[],New,"{'totalSales': 0, 'totalRevenue': 0, 'averageRating': 0, 'totalReviews': 0}","[{'public_id': 'zatch/products/1770926647137-88663491.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926647137-88663491.jpg', '_id': {'$oid': '698e323a2c63bfbc0476a8b7'}}, {'public_id': 'zatch/products/1770926648199-146079028.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926648199-146079028.jpg', '_id': {'$oid': '698e323a2c63bfbc0476a8b8'}}, {'public_id': 'zatch/products/1770926648490-777930851.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1770926648490-777930851.jpg', '_id': {'$oid': '698e323a2c63bfbc0476a8b9'}}]","[{'color': 'brown', 'size': 'MEDIUM', 'stock': 16, 'isOutOfStock': False, 'images': [{'public_id': 'zatch/products/variants/1770926648909-745129509.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926648909-745129509.jpg', '_id': {'$oid': '698e323e2c63bfbc0476a8e1'}}, {'public_id': 'zatch/products/variants/1770926649174-709929561.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926649174-709929561.jpg', '_id': {'$oid': '698e323e2c63bfbc0476a8e2'}}, {'public_id': 'zatch/products/variants/1770926649461-616656970.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1770926649461-616656970.jpg', '_id': {'$oid': '698e323e2c63bfbc0476a8e3'}}]}]",[],[],Turtleneck shirts,Turtleneck shirts,999,899,Men,tshirts-polos,{'$date': '2026-02-12T20:03:45.41Z'},{'$date': '2026-05-30T17:21:59.962Z'},GEN-698E32,2,NaN,NaN
2,{'$oid': '698e33212c63bfbc0476ae08'},{'$oid': '698e25132c63bfbc047683d8'},0,15,Products,"{'hasSize': True, 'hasColor': True, 'hasVariants': True}","{'step1': {'bargainSettings': {'autoAcceptDiscount': 5, 'maximumDiscount': 30}, 'category': 'Men', 'subCategory': 'casual-shirts', 'name': 'Leather jacket ', 'description': 'Leather jacket ', 'price': 1499, 'discountedPrice': 650, 'totalStock': 15, 'hasSize': True, 'hasColor': True}, 'step2': {'colors': ['brown']}, 'step3': {'images': [{'public_id': 'zatch/products/1772292965822-577929995.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1772292965822-577929995.jpg', '_id': {'$oid': '69a30b681efc346e038ae8f9'}}, {'public_id': 'zatch/products/1772292967055-752661933.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1772292967055-752661933.jpg', '_id': {'$oid': '69a30b681efc346e038ae8fa'}}, {'public_id': 'zatch/products/1772292967268-799924686.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1772292967268-799924686.jpg', '_id': {'$oid': '69a30b681efc346e038ae8fb'}}], 'sizes': ['MEDIUM'], 'variantImages': {'brown': {'MEDIUM': [{'public_id': 'zatch/products/variants/1772292967570-889869921.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1772292967570-889869921.jpg'}, {'public_id': 'zatch/products/variants/1772292967800-205049170.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1772292967800-205049170.jpg'}, {'public_id': 'zatch/products/variants/1772292968051-865280514.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1772292968051-865280514.jpg'}]}}}}",autoAccept,"{'freeShipping': False, 'estimatedDeliveryDays': 7, 'codAvailable': False, 'returnPolicy': '7 days return policy'}",False,NaN,False,NaN,0,0,36,inactive,"{'autoAcceptDiscount': 5, 'maximumDiscount': 30}",[],[],New,"{'totalSales': 0, 'totalRevenue': 0, 'averageRating': 0, 'totalReviews': 0}","[{'public_id': 'zatch/products/1772292965822-577929995.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1772292965822-577929995.jpg', '_id': {'$oid': '69a30b681efc346e038ae8fc'}}, {'public_id': 'zatch/products/1772292967055-752661933.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1772292967055-752661933.jpg', '_id': {'$oid': '69a30b681efc346e038ae8fd'}}, {'public_id': 'zatch/products/1772292967268-799924686.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/1772292967268-799924686.jpg', '_id': {'$oid': '69a30b681efc346e038ae8fe'}}]","[{'color': 'brown', 'size': 'MEDIUM', 'stock': 14, 'isOutOfStock': False, 'images': [{'public_id': 'zatch/products/variants/1772292967570-889869921.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1772292967570-889869921.jpg', '_id': {'$oid': '69a30b691efc346e038ae90b'}}, {'public_id': 'zatch/products/variants/1772292967800-205049170.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1772292967800-205049170.jpg', '_id': {'$oid': '69a30b691efc346e038ae90c'}}, {'public_id': 'zatch/products/variants/1772292968051-865280514.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/products/variants/1772292968051-865280514.jpg', '_id': {'$oid': '69a30b691efc346e038ae90d'}}]}]",[],[],Leather jacket,Leather jacket,1499,650,Men,casual-shirts,{'$date': '2026-02-12T20:08:01.175Z'},{'$date': '2026-05-30T17:21:58.905Z'},GEN-698E33,10,NaN,NaN

,_id,username,password,countryCode,phone,email,profilePic,gender,categoryType,sellerProfile,sellerStatus,globalBargainSettings,shoppingPreferences,followers,following,followerCount,reviewsCount,productsSoldCount,customerRating,savedBits,savedProducts,likedProducts,isAdmin,createdAt,searchHistory,__v,dob,role,refreshToken,refreshTokenExpiry,phoneOtp,phoneOtpExpiry,emailOtp,emailOtpExpiry
0,{'$oid': '698e25132c63bfbc047683d8'},krish,$2b$10$VxOLvwfS7bI8XezZrQcN/OHceU0uqJhlT5pTuo7KsHUwEeb8nA9qS,91,9705689166,krishneshcmv03@gmail.com,"{'public_id': 'zatch/profiles/1771673259490-37378078.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/profiles/1771673259490-37378078.jpg'}",Male,People,"{'tcAccepted': True, 'documents': [], 'businessName': 'zirus', 'address': {'billingAddress': 'Bangalore', 'latitude': 12.9603582, 'longitude': 77.7159565, 'pickupAddress': 'Bangalore', 'pinCode': '560064', 'state': 'Karnataka'}, 'shippingMethod': 'self_ship', 'bankDetails': {'accountHolderName': 'C M V Krishnesh', 'accountNumber': '003312010000305', 'bankName': 'Union Bank of India', 'ifscCode': 'UBIN0800333', 'upiId': '9705689166@ptyes'}, 'rejectionMessage': 'test'}",rejected,"{'enabled': False, 'autoAcceptDiscount': None, 'maximumDiscount': None}","{'categories': ['Men', 'Women'], 'savedAt': {'$date': '2026-02-20T15:24:16.768Z'}, 'updatedAt': {'$date': '2026-05-21T14:11:36.459Z'}}","[{'$oid': '698e259d2c63bfbc04768479'}, {'$oid': '69a001c31efc346e038a8bfc'}]","[{'$oid': '698e264a2c63bfbc04768582'}, {'$oid': '6995bf9a530ccacc606d365f'}, {'$oid': '6992fed22c63bfbc04771576'}, {'$oid': '69902d022c63bfbc0476da36'}, {'$oid': '69f3795668f7e97ef43f6ada'}]",2,0,20,0,"[{'$oid': '69929d6c2c63bfbc0477144c'}, {'$oid': '6a097fdfb7bb9861659c9a20'}]","[{'$oid': '6995d3468c1ab0f14cb59635'}, {'$oid': '6999d5543ec6020eaac6152d'}, {'$oid': '69b1521dc203397431aea37e'}, {'$oid': '6a080d3e1a9ba20ae97eaf56'}]",[{'$oid': '698e32212c63bfbc0476a7f2'}],False,{'$date': '2026-02-12T19:08:03.577Z'},[],17,{'$date': '2000-04-03T00:00:00Z'},user,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OThlMjUxMzJjNjNiZmJjMDQ3NjgzZDgiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc4MDE2MTY4OCwiZXhwIjoxNzgyNzUzNjg4fQ.QR2KbaWWLeUfTdH01rm4GBaKDbv9AF2RRW5NukzyNdA,{'$date': '2026-06-29T17:21:28.428Z'},NaN,NaN,NaN,NaN
1,{'$oid': '698e259d2c63bfbc04768479'},Pavan,$2b$10$9RZvOHvBSLlUTDjioHDGRuuw2hqFFdlnr97ZOtlMJhQcgmZV/pf7i,91,9515101099,pavankumarreddyrachamreddy2004@gmail.com,"{'public_id': '', 'url': ''}",Male,People,"{'tcAccepted': True, 'documents': [], 'businessName': 'thrive fashions', 'address': {'billingAddress': 'Itgalpur Rajanakunte, Yelahanka, Bengaluru, Ittagallpura, Karnataka 560119, India, Itgalpur Rajanakunte, Yelahanka, Bengaluru, Ittagallpura, Karnataka 560119, India', 'latitude': 14.7630565, 'longitude': 78.5557699, 'pickupAddress': 'Itgalpur Rajanakunte, Yelahanka, Bengaluru, Ittagallpura, Karnataka 560119, India, Itgalpur Rajanakunte, Yelahanka, Bengaluru, Ittagallpura, Karnataka 560119, India', 'pinCode': '516360', 'state': 'Andhra Pradesh'}, 'shippingMethod': 'self_ship', 'bankDetails': {'accountHolderName': 'Pavan Kumar reddy', 'accountNumber': '25025803800', 'bankName': 'HDFC Bank', 'ifscCode': 'HDFC0001013', 'upiId': ''}}",active,"{'enabled': False, 'autoAcceptDiscount': None, 'maximumDiscount': None}","{'categories': ['Women'], 'savedAt': {'$date': '2026-02-20T15:55:26.247Z'}, 'updatedAt': {'$date': '2026-05-21T21:23:17.694Z'}}",[{'$oid': '69a001c31efc346e038a8bfc'}],"[{'$oid': '698e25132c63bfbc047683d8'}, {'$oid': '6995bf9a530ccacc606d365f'}, {'$oid': '699308462c63bfbc04771685'}, {'$oid': '6a084ac71a9ba20ae97f5f37'}]",1,0,18,0,"[{'$oid': '69aac90f4e2d6530993b50a6'}, {'$oid': '69ece24543cd9b163f98247f'}]","[{'$oid': '699aa83a3ec6020eaac633af'}, {'$oid': '69a1ad211efc346e038a9611'}]",[],False,{'$date': '2026-02-12T19:10:21.362Z'},[],25,NaN,user,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OThlMjU5ZDJjNjNiZmJjMDQ3Njg0NzkiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc4MDg1NzY2NSwiZXhwIjoxNzgzNDQ5NjY1fQ.UgjFtUjlCWBZQZMATHsnqVFvSDmQy6iVwoA6tPplXro,{'$date': '2026-07-07T18:41:05.726Z'},NaN,NaN,NaN,NaN
2,{'$oid': '698e263e2c63bfbc0476857e'},Wamika,$2b$10$gOF6wGVIkV3gsGTvVwAU9eXrPkJAFd9tQ1Ks7480AhG1nLPMr1gsK,91,9010490404,wregonda@gmail.com,"{'public_id': 'zatch/profiles/1775805012121-327962621.jpg', 'url': 'https://zatchP.b-cdn.net/zatch/profiles/1775805012121-327962621.jpg'}",Female,People,"{'tcAccepted': False, 'documents': [], 'businessName': 'Rakshit Test'}",buyer,"{'enabled': False, 'autoAcceptDiscount': 5, 'maximumDiscount': 10}","{'categories': ['Home', 'Women', 'beauty and personal care', 'bed-bath'], 'savedAt': {'$date': '2026-02-21T22:22:30.691Z'}, 'updatedAt': {'$date': '2026-05-07T21:00:44.345Z'}}",[],[{'$oid': '69902d022c63bfbc0476da36'}],0,0,0,0,[{'$oid': '69b99c44d5ba7b8d34df60eb'}],[{'$oid': '69b9a311d5ba7b8d34df6f02'}],[],False,{'$date': '2026-02-12T19:13:02.229Z'},[],7,{'$date': '2001-06-10T00:00:00Z'},user,eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2OThlMjYzZTJjNjNiZmJjMDQ3Njg1N2UiLCJ0eXBlIjoicmVmcmVzaCIsImlhdCI6MTc4MDY3NzQzNywiZXhwIjoxNzgzMjY5NDM3fQ.P2ilzdKXCyxV2LDDF9SJ1FkiY7Ls4adA9NwpfnyyGd4,{'$date': '2026-07-05T16:37:17.956Z'},NaN,NaN,NaN,NaN

,_id,userId,bitId,watchedMs,totalDurationMs,watchPercent,completedWatch,rewatched,replayCount,pauseCount,soundOn,tappedProduct,scrolledToProduct,addedToCart,likedDuringWatch,sharedDuringWatch,source,deviceType,timestamp,__v
0,{'$oid': '6a08bb67b7bb9861659c3e29'},{'$oid': '69f8608068f7e97ef44183e4'},{'$oid': '6a08bb2eb7bb9861659c3e06'},0,0,0,False,False,0,0,True,NaN,False,False,False,True,feed,android,{'$date': '2026-05-16T18:45:59.497Z'},0
1,{'$oid': '6a0d9d87d4f03db64a7921bf'},{'$oid': '6a084ac71a9ba20ae97f5f37'},{'$oid': '6a0c58c8d4f03db64a788ccd'},0,0,0,False,False,0,0,True,NaN,False,False,False,True,feed,android,{'$date': '2026-05-20T11:39:51.525Z'},0
2,{'$oid': '6a0d9d88d4f03db64a7921c4'},{'$oid': '6a084ac71a9ba20ae97f5f37'},{'$oid': '6a0c58c8d4f03db64a788ccd'},0,0,0,False,False,0,0,True,NaN,False,False,False,True,feed,android,{'$date': '2026-05-20T11:39:52.968Z'},0

In [8]:
# INSPECT MONGODB FIELDS

print("BITS _id")
display(bits_df["_id"].head())

print("\nBITS userId")
display(bits_df["userId"].head())

print("\nBITS products")
display(bits_df["products"].head())

print("\nPRODUCTS _id")
display(products_df["_id"].head())

print("\nPRODUCTS sellerId")
display(products_df["sellerId"].head())

print("\nREELVIEWS userId")
display(reelviews_df["userId"].head())

print("\nREELVIEWS bitId")
display(reelviews_df["bitId"].head())

BITS _id

0    {'$oid': '698e30532c63bfbc04769c5e'}
1    {'$oid': '698e32a92c63bfbc0476ab3b'}
2    {'$oid': '698e33892c63bfbc0476b11f'}
3    {'$oid': '69a31d440a0ce3fd3a6bc51f'}
4    {'$oid': '69a330f30a0ce3fd3a6be9b0'}
Name: _id, dtype: object

BITS userId

0    {'$oid': '698e25132c63bfbc047683d8'}
1    {'$oid': '698e25132c63bfbc047683d8'}
2    {'$oid': '698e25132c63bfbc047683d8'}
3    {'$oid': '698e25132c63bfbc047683d8'}
4    {'$oid': '698e25132c63bfbc047683d8'}
Name: userId, dtype: object

BITS products

0    [{'$oid': '698e2fc02c63bfbc047698b2'}]
1    [{'$oid': '698e32212c63bfbc0476a7f2'}]
2    [{'$oid': '698e33212c63bfbc0476ae08'}]
3    [{'$oid': '698e33212c63bfbc0476ae08'}]
4    [{'$oid': '698e33212c63bfbc0476ae08'}]
Name: products, dtype: object

PRODUCTS _id

0    {'$oid': '698e2fc02c63bfbc047698b2'}
1    {'$oid': '698e32212c63bfbc0476a7f2'}
2    {'$oid': '698e33212c63bfbc0476ae08'}
3    {'$oid': '6995d3468c1ab0f14cb59635'}
4    {'$oid': '69988931722cd8db737026d5'}
Name: _id, dtype: object

PRODUCTS sellerId

0    {'$oid': '698e25132c63bfbc047683d8'}
1    {'$oid': '698e25132c63bfbc047683d8'}
2    {'$oid': '698e25132c63bfbc047683d8'}
3    {'$oid': '698e264a2c63bfbc04768582'}
4    {'$oid': '6992fed22c63bfbc04771576'}
Name: sellerId, dtype: object

REELVIEWS userId

0    {'$oid': '69f8608068f7e97ef44183e4'}
1    {'$oid': '6a084ac71a9ba20ae97f5f37'}
2    {'$oid': '6a084ac71a9ba20ae97f5f37'}
3    {'$oid': '698e259d2c63bfbc04768479'}
4    {'$oid': '698e259d2c63bfbc04768479'}
Name: userId, dtype: object

REELVIEWS bitId

0    {'$oid': '6a08bb2eb7bb9861659c3e06'}
1    {'$oid': '6a0c58c8d4f03db64a788ccd'}
2    {'$oid': '6a0c58c8d4f03db64a788ccd'}
3    {'$oid': '6a0efe70c5a9d08fea4c67cf'}
4    {'$oid': '6a0febf65ecfbb647dcf6c6f'}
Name: bitId, dtype: object

In [9]:
# MONGODB OBJECTID CLEANER

import ast

def extract_objectid(value):

    if pd.isna(value):
        return np.nan

    try:
        data = ast.literal_eval(value)

        if isinstance(data, dict):
            return data.get("$oid")

    except:
        pass

    return value

In [10]:
# TEST OBJECTID CLEANER

sample_id = bits_df["_id"].iloc[0]

print("Before:")
print(sample_id)

print("\nAfter:")
print(extract_objectid(sample_id))

Before:
{'$oid': '698e30532c63bfbc04769c5e'}

After:
698e30532c63bfbc04769c5e

In [11]:
# CLEAN SINGLE OBJECTID COLUMNS

bits_df["_id"] = bits_df["_id"].apply(extract_objectid)
bits_df["userId"] = bits_df["userId"].apply(extract_objectid)

products_df["_id"] = products_df["_id"].apply(extract_objectid)
products_df["sellerId"] = products_df["sellerId"].apply(extract_objectid)

users_df["_id"] = users_df["_id"].apply(extract_objectid)

reelviews_df["_id"] = reelviews_df["_id"].apply(extract_objectid)
reelviews_df["userId"] = reelviews_df["userId"].apply(extract_objectid)
reelviews_df["bitId"] = reelviews_df["bitId"].apply(extract_objectid)

print("Single ObjectIds Cleaned")

Single ObjectIds Cleaned

In [12]:
# VERIFY CLEANING

print(bits_df["_id"].head())

print("\n")

print(products_df["_id"].head())

print("\n")

print(users_df["_id"].head())

print("\n")

print(reelviews_df["userId"].head())

0    698e30532c63bfbc04769c5e
1    698e32a92c63bfbc0476ab3b
2    698e33892c63bfbc0476b11f
3    69a31d440a0ce3fd3a6bc51f
4    69a330f30a0ce3fd3a6be9b0
Name: _id, dtype: object


0    698e2fc02c63bfbc047698b2
1    698e32212c63bfbc0476a7f2
2    698e33212c63bfbc0476ae08
3    6995d3468c1ab0f14cb59635
4    69988931722cd8db737026d5
Name: _id, dtype: object


0    698e25132c63bfbc047683d8
1    698e259d2c63bfbc04768479
2    698e263e2c63bfbc0476857e
3    698e264a2c63bfbc04768582
4    698e269c2c63bfbc04768709
Name: _id, dtype: object


0    69f8608068f7e97ef44183e4
1    6a084ac71a9ba20ae97f5f37
2    6a084ac71a9ba20ae97f5f37
3    698e259d2c63bfbc04768479
4    698e259d2c63bfbc04768479
Name: userId, dtype: object

In [13]:
# PRODUCT LIST CLEANER

def extract_objectid_list(value):

    if pd.isna(value):
        return []

    try:

        data = ast.literal_eval(value)

        if isinstance(data, list):

            cleaned_ids = []

            for item in data:

                if isinstance(item, dict):

                    oid = item.get("$oid")

                    if oid:
                        cleaned_ids.append(oid)

            return cleaned_ids

    except:
        pass

    return []

In [14]:
# CLEAN PRODUCTS COLUMN

bits_df["products"] = bits_df["products"].apply(
    extract_objectid_list
)

print("Products Column Cleaned")

Products Column Cleaned

In [15]:
# VERIFY PRODUCTS COLUMN

display(
    bits_df[["_id", "products"]].head(10)
)

,_id,products
0,698e30532c63bfbc04769c5e,[698e2fc02c63bfbc047698b2]
1,698e32a92c63bfbc0476ab3b,[698e32212c63bfbc0476a7f2]
2,698e33892c63bfbc0476b11f,[698e33212c63bfbc0476ae08]
3,69a31d440a0ce3fd3a6bc51f,[698e33212c63bfbc0476ae08]
4,69a330f30a0ce3fd3a6be9b0,[698e33212c63bfbc0476ae08]
5,69a3e4130a0ce3fd3a6c2507,"[6999d5543ec6020eaac6152d, 6995d3468c1ab0f14cb59635]"
6,69a43b900a0ce3fd3a6c35e9,[]
7,69a69a9d0a0ce3fd3a6cae83,[69988931722cd8db737026d5]
8,69a997184e2d6530993ae84c,[6999d5543ec6020eaac6152d]
9,69aac90f4e2d6530993b50a6,[69a846974e2d6530993ab1c1]

In [16]:
# PRODUCT LIST STATISTICS

bits_df["product_count"] = bits_df["products"].apply(len)

print(
    bits_df["product_count"]
    .value_counts()
    .sort_index()
)

product_count
0      1
1     78
2      3
3      1
4      2
10     2
Name: count, dtype: int64

## Dublicate Record Checking

In [17]:
datasets = {
    "BITS": bits_df,
    "PRODUCTS": products_df,
    "USERS": users_df,
    "REELVIEWS": reelviews_df
}

for name, df in datasets.items():

    print(f"\n{name}")

    temp_df = df.copy()

    # Convert list columns to string
    for col in temp_df.columns:

        if temp_df[col].apply(
            lambda x: isinstance(x, list)
        ).any():

            temp_df[col] = temp_df[col].astype(str)

    print(
        "Duplicate Rows:",
        temp_df.duplicated().sum()
    )

BITS
Duplicate Rows: 0

PRODUCTS
Duplicate Rows: 0

USERS
Duplicate Rows: 0

REELVIEWS
Duplicate Rows: 0

In [18]:
# PRIMARY KEY CHECK

print("BITS IDs:", bits_df["_id"].duplicated().sum())

print("PRODUCT IDs:", products_df["_id"].duplicated().sum())

print("USER IDs:", users_df["_id"].duplicated().sum())

print("REELVIEW IDs:", reelviews_df["_id"].duplicated().sum())

BITS IDs: 0
PRODUCT IDs: 0
USER IDs: 0
REELVIEW IDs: 0

## MISSING VALUE ANALYSIS

In [19]:
for name, df in datasets.items():

    print("\n")
    print("=" * 50)
    print(name)
    print("=" * 50)

    missing = df.isnull().sum()

    missing = missing[missing > 0]

    if len(missing) == 0:

        print("No Missing Values")

    else:

        display(
            missing.sort_values(
                ascending=False
            )
        )

==================================================
BITS
==================================================

description    5
dtype: int64

==================================================
PRODUCTS
==================================================

soldAt              106
topPickExpiresAt    106
productCategory     102
hsn                  85
dtype: int64

==================================================
USERS
==================================================

emailOtp              140
emailOtpExpiry        140
phoneOtp              139
phoneOtpExpiry        139
dob                   127
refreshToken           48
refreshTokenExpiry     48
dtype: int64

==================================================
REELVIEWS
==================================================

tappedProduct    11
dtype: int64

In [20]:
# INSPECT IMPORTANT COLUMNS

columns_to_check = {

    "BITS": [
        "hashtags",
        "likes",
        "comments"
    ],

    "USERS": [
        "followers",
        "following",
        "savedBits",
        "savedProducts",
        "likedProducts",
        "searchHistory"
    ]
}

for dataset_name, cols in columns_to_check.items():

    print("\n")
    print("="*70)
    print(dataset_name)
    print("="*70)

    df = bits_df if dataset_name == "BITS" else users_df

    for col in cols:

        print(f"\nCOLUMN: {col}")

        display(df[col].head(3))

======================================================================
BITS
======================================================================

COLUMN: hashtags

0       ['#pants', '#italian', '#style']
1    ['#turtleneck', '#fashion', '#men']
2      ['#jacket', '#fashion', '#style']
Name: hashtags, dtype: object

COLUMN: likes

0                                          [{'$oid': '698e259d2c63bfbc04768479'}, {'$oid': '698e25132c63bfbc047683d8'}]
1    [{'$oid': '698e259d2c63bfbc04768479'}, {'$oid': '698e6cbe2c63bfbc0476bfa7'}, {'$oid': '699db7d01efc346e038a285b'}]
2    [{'$oid': '698e259d2c63bfbc04768479'}, {'$oid': '698e6cbe2c63bfbc0476bfa7'}, {'$oid': '69a001c31efc346e038a8bfc'}]
Name: likes, dtype: object

COLUMN: comments

0    [{'userId': {'$oid': '698e25132c63bfbc047683d8'}, 'text': 'ygbhi', '_id': {'$oid': '69b8492cd5ba7b8d34deeef7'}, 'createdAt': {'$date': '2026-03-16T18:17:16.392Z'}}]
1                                                                                                                                                                      []
2                                                                                                                                                                      []
Name: comments, dtype: object

======================================================================
USERS
======================================================================

COLUMN: followers

0    [{'$oid': '698e259d2c63bfbc04768479'}, {'$oid': '69a001c31efc346e038a8bfc'}]
1                                          [{'$oid': '69a001c31efc346e038a8bfc'}]
2                                                                              []
Name: followers, dtype: object

COLUMN: following

0    [{'$oid': '698e264a2c63bfbc04768582'}, {'$oid': '6995bf9a530ccacc606d365f'}, {'$oid': '6992fed22c63bfbc04771576'}, {'$oid': '69902d022c63bfbc0476da36'}, {'$oid': '69f3795668f7e97ef43f6ada'}]
1                                          [{'$oid': '698e25132c63bfbc047683d8'}, {'$oid': '6995bf9a530ccacc606d365f'}, {'$oid': '699308462c63bfbc04771685'}, {'$oid': '6a084ac71a9ba20ae97f5f37'}]
2                                                                                                                                                            [{'$oid': '69902d022c63bfbc0476da36'}]
Name: following, dtype: object

COLUMN: savedBits

0    [{'$oid': '69929d6c2c63bfbc0477144c'}, {'$oid': '6a097fdfb7bb9861659c9a20'}]
1    [{'$oid': '69aac90f4e2d6530993b50a6'}, {'$oid': '69ece24543cd9b163f98247f'}]
2                                          [{'$oid': '69b99c44d5ba7b8d34df60eb'}]
Name: savedBits, dtype: object

COLUMN: savedProducts

0    [{'$oid': '6995d3468c1ab0f14cb59635'}, {'$oid': '6999d5543ec6020eaac6152d'}, {'$oid': '69b1521dc203397431aea37e'}, {'$oid': '6a080d3e1a9ba20ae97eaf56'}]
1                                                                                [{'$oid': '699aa83a3ec6020eaac633af'}, {'$oid': '69a1ad211efc346e038a9611'}]
2                                                                                                                      [{'$oid': '69b9a311d5ba7b8d34df6f02'}]
Name: savedProducts, dtype: object

COLUMN: likedProducts

0    [{'$oid': '698e32212c63bfbc0476a7f2'}]
1                                        []
2                                        []
Name: likedProducts, dtype: object

COLUMN: searchHistory

0    []
1    []
2    []
Name: searchHistory, dtype: object

In [21]:
# REELVIEW BEHAVIOUR SAMPLE

display(
    reelviews_df[
        [
            "watchPercent",
            "completedWatch",
            "rewatched",
            "replayCount",
            "pauseCount",
            "tappedProduct",
            "addedToCart",
            "likedDuringWatch",
            "sharedDuringWatch"
        ]
    ].head(10)
)

,watchPercent,completedWatch,rewatched,replayCount,pauseCount,tappedProduct,addedToCart,likedDuringWatch,sharedDuringWatch
0,0,False,False,0,0,NaN,False,False,True
1,0,False,False,0,0,NaN,False,False,True
2,0,False,False,0,0,NaN,False,False,True
3,0,False,False,0,0,NaN,False,False,False
4,0,False,False,0,0,NaN,False,False,False
5,0,False,False,0,0,{'$oid': '6a0febf65ecfbb647dcf6c6f'},False,False,False
6,0,False,True,0,0,{'$oid': '6a0efe70c5a9d08fea4c67cf'},False,False,False
7,0,False,True,0,0,{'$oid': '6a0efe70c5a9d08fea4c67cf'},False,False,False
8,0,False,False,0,0,NaN,False,False,False
9,0,False,False,0,0,NaN,False,False,False

In [22]:
# LIST LENGTH EXTRACTOR

def get_list_length(value):

    if pd.isna(value):
        return 0

    try:

        data = ast.literal_eval(value)

        if isinstance(data, list):
            return len(data)

    except:
        pass

    return 0

In [23]:
# BITS ENGAGEMENT FEATURES

bits_df["likes_count_actual"] = (
    bits_df["likes"]
    .apply(get_list_length)
)

bits_df["comments_count_actual"] = (
    bits_df["comments"]
    .apply(get_list_length)
)

print("Bits Engagement Features Created")

Bits Engagement Features Created

In [24]:
# USER FEATURES

users_df["followers_count_actual"] = (
    users_df["followers"]
    .apply(get_list_length)
)

users_df["following_count_actual"] = (
    users_df["following"]
    .apply(get_list_length)
)

users_df["saved_bits_count"] = (
    users_df["savedBits"]
    .apply(get_list_length)
)

users_df["saved_products_count"] = (
    users_df["savedProducts"]
    .apply(get_list_length)
)

users_df["liked_products_count"] = (
    users_df["likedProducts"]
    .apply(get_list_length)
)

print("User Features Created")

User Features Created

In [25]:
# FEATURE VALIDATION
display(

    bits_df[
        [
            "title",
            "likeCount",
            "likes_count_actual",
            "comments_count_actual"
        ]
    ].head()

)

display(

    users_df[
        [
            "username",
            "followerCount",
            "followers_count_actual",
            "following_count_actual",
            "saved_bits_count",
            "saved_products_count"
        ]
    ].head()

)

,title,likeCount,likes_count_actual,comments_count_actual
0,Italian pants,2,2,1
1,Turtleneck shirts,3,3,0
2,Leather jacket,3,3,0
3,Accessories u may like,1,1,0
4,Accessories u may like,1,1,0

,username,followerCount,followers_count_actual,following_count_actual,saved_bits_count,saved_products_count
0,krish,2,2,5,2,4
1,Pavan,1,1,4,2,2
2,Wamika,0,0,1,1,1
3,nishithaa!,2,2,1,1,0
4,lucky,0,0,0,0,0

In [26]:
# INSPECT DATE COLUMNS

print("BITS createdAt")
display(bits_df["createdAt"].head())

print("\nPRODUCTS createdAt")
display(products_df["createdAt"].head())

print("\nUSERS createdAt")
display(users_df["createdAt"].head())

print("\nREELVIEWS timestamp")
display(reelviews_df["timestamp"].head())

BITS createdAt

0    {'$date': '2026-02-12T19:56:03.694Z'}
1    {'$date': '2026-02-12T20:06:01.538Z'}
2    {'$date': '2026-02-12T20:09:45.068Z'}
3    {'$date': '2026-02-28T16:52:20.239Z'}
4    {'$date': '2026-02-28T18:16:19.152Z'}
Name: createdAt, dtype: object

PRODUCTS createdAt

0     {'$date': '2026-02-12T19:53:36.12Z'}
1     {'$date': '2026-02-12T20:03:45.41Z'}
2    {'$date': '2026-02-12T20:08:01.175Z'}
3     {'$date': '2026-02-18T14:57:10.38Z'}
4    {'$date': '2026-02-20T16:17:53.363Z'}
Name: createdAt, dtype: object

USERS createdAt

0    {'$date': '2026-02-12T19:08:03.577Z'}
1    {'$date': '2026-02-12T19:10:21.362Z'}
2    {'$date': '2026-02-12T19:13:02.229Z'}
3    {'$date': '2026-02-12T19:13:14.032Z'}
4    {'$date': '2026-02-12T19:14:36.387Z'}
Name: createdAt, dtype: object

REELVIEWS timestamp

0    {'$date': '2026-05-16T18:45:59.497Z'}
1    {'$date': '2026-05-20T11:39:51.525Z'}
2    {'$date': '2026-05-20T11:39:52.968Z'}
3    {'$date': '2026-05-22T06:37:24.594Z'}
4    {'$date': '2026-05-22T06:37:25.021Z'}
Name: timestamp, dtype: object

In [27]:
# DATE FORMAT SAMPLE

print(bits_df["createdAt"].iloc[0])
print(products_df["createdAt"].iloc[0])
print(users_df["createdAt"].iloc[0])
print(reelviews_df["timestamp"].iloc[0])

{'$date': '2026-02-12T19:56:03.694Z'}
{'$date': '2026-02-12T19:53:36.12Z'}
{'$date': '2026-02-12T19:08:03.577Z'}
{'$date': '2026-05-16T18:45:59.497Z'}

In [28]:
# MONGODB DATE CLEANER

def extract_mongo_date(value):

    if pd.isna(value):
        return pd.NaT

    try:

        data = ast.literal_eval(value)

        if isinstance(data, dict):

            date_value = data.get("$date")

            return pd.to_datetime(
                date_value,
                errors="coerce"
            )

    except:
        pass

    return pd.NaT

In [29]:
# VERIFY DATETIME CONVERSION

print(bits_df["createdAt"].head())

print("\nDatatype:")
print(bits_df["createdAt"].dtype)

print("\n")

print(reelviews_df["timestamp"].head())

print("\nDatatype:")
print(reelviews_df["timestamp"].dtype)

0    {'$date': '2026-02-12T19:56:03.694Z'}
1    {'$date': '2026-02-12T20:06:01.538Z'}
2    {'$date': '2026-02-12T20:09:45.068Z'}
3    {'$date': '2026-02-28T16:52:20.239Z'}
4    {'$date': '2026-02-28T18:16:19.152Z'}
Name: createdAt, dtype: object

Datatype:
object


0    {'$date': '2026-05-16T18:45:59.497Z'}
1    {'$date': '2026-05-20T11:39:51.525Z'}
2    {'$date': '2026-05-20T11:39:52.968Z'}
3    {'$date': '2026-05-22T06:37:24.594Z'}
4    {'$date': '2026-05-22T06:37:25.021Z'}
Name: timestamp, dtype: object

Datatype:
object

In [30]:
# DEBUG DATE VALUE

sample = bits_df["createdAt"].iloc[0]

print(type(sample))
print(sample)

<class 'str'>
{'$date': '2026-02-12T19:56:03.694Z'}

In [31]:
# ROBUST MONGODB DATE CLEANER

import re

def extract_mongo_date(value):

    if pd.isna(value):
        return pd.NaT

    value = str(value)

    match = re.search(
        r"'\$date':\s*'([^']+)'",
        value
    )

    if match:

        return pd.to_datetime(
            match.group(1),
            errors="coerce"
        )

    return pd.NaT

In [32]:
# RE-CLEAN DATE COLUMNS

bits_df["createdAt"] = bits_df["createdAt"].apply(
    extract_mongo_date
)

products_df["createdAt"] = products_df["createdAt"].apply(
    extract_mongo_date
)

products_df["updatedAt"] = products_df["updatedAt"].apply(
    extract_mongo_date
)

users_df["createdAt"] = users_df["createdAt"].apply(
    extract_mongo_date
)

reelviews_df["timestamp"] = reelviews_df["timestamp"].apply(
    extract_mongo_date
)

print("Date Cleaning Completed")

Date Cleaning Completed

In [33]:
# VERIFY DATE CLEANING

print(bits_df["createdAt"].head())

print("\nDatatype:")
print(bits_df["createdAt"].dtype)

print("\n")

print(reelviews_df["timestamp"].head())

print("\nDatatype:")
print(reelviews_df["timestamp"].dtype)

0   2026-02-12 19:56:03.694000+00:00
1   2026-02-12 20:06:01.538000+00:00
2   2026-02-12 20:09:45.068000+00:00
3   2026-02-28 16:52:20.239000+00:00
4   2026-02-28 18:16:19.152000+00:00
Name: createdAt, dtype: datetime64[ns, UTC]

Datatype:
datetime64[ns, UTC]


0   2026-05-16 18:45:59.497000+00:00
1   2026-05-20 11:39:51.525000+00:00
2   2026-05-20 11:39:52.968000+00:00
3   2026-05-22 06:37:24.594000+00:00
4   2026-05-22 06:37:25.021000+00:00
Name: timestamp, dtype: datetime64[ns, UTC]

Datatype:
datetime64[ns, UTC]

In [34]:
# TIME FEATURES

bits_df["created_year"] = (
    bits_df["createdAt"].dt.year
)

bits_df["created_month"] = (
    bits_df["createdAt"].dt.month
)

bits_df["created_day"] = (
    bits_df["createdAt"].dt.day
)

reelviews_df["watch_year"] = (
    reelviews_df["timestamp"].dt.year
)

reelviews_df["watch_month"] = (
    reelviews_df["timestamp"].dt.month
)

reelviews_df["watch_day"] = (
    reelviews_df["timestamp"].dt.day
)

print("Time Features Created")

Time Features Created

In [35]:
# VERIFY TIME FEATURES

display(

    bits_df[
        [
            "createdAt",
            "created_year",
            "created_month",
            "created_day"
        ]
    ].head()

)

display(

    reelviews_df[
        [
            "timestamp",
            "watch_year",
            "watch_month",
            "watch_day"
        ]
    ].head()

)

                         createdAt  created_year  created_month  created_day
0 2026-02-12 19:56:03.694000+00:00          2026              2           12
1 2026-02-12 20:06:01.538000+00:00          2026              2           12
2 2026-02-12 20:09:45.068000+00:00          2026              2           12
3 2026-02-28 16:52:20.239000+00:00          2026              2           28
4 2026-02-28 18:16:19.152000+00:00          2026              2           28

                         timestamp  watch_year  watch_month  watch_day
0 2026-05-16 18:45:59.497000+00:00        2026            5         16
1 2026-05-20 11:39:51.525000+00:00        2026            5         20
2 2026-05-20 11:39:52.968000+00:00        2026            5         20
3 2026-05-22 06:37:24.594000+00:00        2026            5         22
4 2026-05-22 06:37:25.021000+00:00        2026            5         22

In [36]:
# WATCH SCORE
reelviews_df["watch_score"] = (

    reelviews_df["watchPercent"] * 0.40 +

    reelviews_df["completedWatch"].astype(int) * 20 +

    reelviews_df["rewatched"].astype(int) * 15 +

    reelviews_df["replayCount"] * 5
)

In [37]:
# INTERACTION SCORE

reelviews_df["interaction_score"] = (

    reelviews_df["likedDuringWatch"].astype(int) * 10 +

    reelviews_df["sharedDuringWatch"].astype(int) * 15 +

    reelviews_df["tappedProduct"].notna().astype(int) * 10 +

    reelviews_df["addedToCart"].astype(int) * 25
)

In [38]:
# FINAL ENGAGEMENT SCORE

reelviews_df["engagement_score"] = (

    reelviews_df["watch_score"]

    +

    reelviews_df["interaction_score"]

)

print("Engagement Features Created")

Engagement Features Created

In [39]:
# ENGAGEMENT FEATURE CHECK

display(

    reelviews_df[
        [
            "watchPercent",
            "completedWatch",
            "rewatched",
            "replayCount",
            "likedDuringWatch",
            "sharedDuringWatch",
            "addedToCart",
            "watch_score",
            "interaction_score",
            "engagement_score"
        ]
    ].head(10)

)

,watchPercent,completedWatch,rewatched,replayCount,likedDuringWatch,sharedDuringWatch,addedToCart,watch_score,interaction_score,engagement_score
0,0,False,False,0,False,True,False,0.0,15,15.0
1,0,False,False,0,False,True,False,0.0,15,15.0
2,0,False,False,0,False,True,False,0.0,15,15.0
3,0,False,False,0,False,False,False,0.0,0,0.0
4,0,False,False,0,False,False,False,0.0,0,0.0
5,0,False,False,0,False,False,False,0.0,10,10.0
6,0,False,True,0,False,False,False,15.0,10,25.0
7,0,False,True,0,False,False,False,15.0,10,25.0
8,0,False,False,0,False,False,False,0.0,0,0.0
9,0,False,False,0,False,False,False,0.0,0,0.0

## Interaction Dataset Preview

In [40]:
# INTERACTION DATASET

interaction_df = reelviews_df[
    [
        "_id",
        "userId",
        "bitId",
        "watchPercent",
        "completedWatch",
        "rewatched",
        "replayCount",
        "likedDuringWatch",
        "sharedDuringWatch",
        "addedToCart",
        "watch_score",
        "interaction_score",
        "engagement_score"
    ]
].copy()

print(interaction_df.shape)

interaction_df.head()

(1659, 13)

,_id,userId,bitId,watchPercent,completedWatch,rewatched,replayCount,likedDuringWatch,sharedDuringWatch,addedToCart,watch_score,interaction_score,engagement_score
0,6a08bb67b7bb9861659c3e29,69f8608068f7e97ef44183e4,6a08bb2eb7bb9861659c3e06,0,False,False,0,False,True,False,0.0,15,15.0
1,6a0d9d87d4f03db64a7921bf,6a084ac71a9ba20ae97f5f37,6a0c58c8d4f03db64a788ccd,0,False,False,0,False,True,False,0.0,15,15.0
2,6a0d9d88d4f03db64a7921c4,6a084ac71a9ba20ae97f5f37,6a0c58c8d4f03db64a788ccd,0,False,False,0,False,True,False,0.0,15,15.0
3,6a0ff9a4fac84b0b7fb94d91,698e259d2c63bfbc04768479,6a0efe70c5a9d08fea4c67cf,0,False,False,0,False,False,False,0.0,0,0.0
4,6a0ff9a5fac84b0b7fb94d99,698e259d2c63bfbc04768479,6a0febf65ecfbb647dcf6c6f,0,False,False,0,False,False,False,0.0,0,0.0

In [41]:
# ENGAGEMENT SCORE STATS

interaction_df["engagement_score"].describe()

count    1659.000000
mean       28.408559
std        15.682849
min         0.000000
25%        17.200000
50%        26.600000
75%        33.000000
max       125.000000
Name: engagement_score, dtype: float64

In [42]:
# TOP ENGAGEMENT RECORDS

interaction_df.sort_values(
    by="engagement_score",
    ascending=False
).head(10)

,_id,userId,bitId,watchPercent,completedWatch,rewatched,replayCount,likedDuringWatch,sharedDuringWatch,addedToCart,watch_score,interaction_score,engagement_score
1246,6a243851849122593d812764,699a2e703ec6020eaac62877,6a0c158bb10aa6108036df86,100,True,True,1,True,False,True,80.0,45,125.0
488,6a188bd6fcdbfad047e3e5e6,69f8608068f7e97ef44183e4,6a0b4336d382a23d66b4511e,100,True,True,3,True,False,False,90.0,20,110.0
108,6a1136c7a9955ce943952cf7,698e259d2c63bfbc04768479,6a0febf65ecfbb647dcf6c6f,100,True,True,2,True,False,False,85.0,20,105.0
1454,6a24c1879984a0ae2e2ca8df,698e259d2c63bfbc04768479,6a0c5c48d4f03db64a78945a,100,True,True,1,True,False,False,80.0,20,100.0
459,6a188a4cfcdbfad047e3e5c6,69f8608068f7e97ef44183e4,69f8fb9568f7e97ef441c429,100,True,False,4,True,False,False,80.0,20,100.0
450,6a188968fcdbfad047e3e5b2,69f8608068f7e97ef44183e4,6a0b4336d382a23d66b4511e,100,True,True,1,True,False,False,80.0,20,100.0
1068,6a22948fad7941493646ccdb,69e51ea68174770ee78f3b81,6a1da45861d3ca2f14751bce,100,True,True,1,True,False,False,80.0,20,100.0
1067,6a229475ad7941493646ccda,69e51ea68174770ee78f3b81,6a0c5c48d4f03db64a78945a,100,True,True,1,True,False,False,80.0,20,100.0
699,6a1b3d1a3724c07c530f3c02,698e259d2c63bfbc04768479,69ece24543cd9b163f98247f,100,True,True,1,True,False,False,80.0,20,100.0
504,6a188cd7fcdbfad047e3e66b,69f8608068f7e97ef44183e4,6a0b4336d382a23d66b4511e,100,True,True,1,True,False,False,80.0,20,100.0

In [43]:
# USER ENGAGEMENT SUMMARY

user_engagement = (

    interaction_df

    .groupby("userId")

    .agg({

        "engagement_score": [
            "count",
            "mean",
            "max"
        ]

    })

)

user_engagement.head()

                         engagement_score
                                    count       mean    max
userId
698e25132c63bfbc047683d8                1  11.600000   11.6
698e259d2c63bfbc04768479              607  31.296540  105.0
698e263e2c63bfbc0476857e              191  27.237696   85.0
698e264a2c63bfbc04768582               10  33.480000   90.0
698e269c2c63bfbc04768709               69  22.965217   90.0

In [44]:
# REEL PERFORMANCE SUMMARY

reel_performance = (

    interaction_df

    .groupby("bitId")

    .agg({

        "engagement_score": [
            "count",
            "mean",
            "max"
        ]

    })

)

reel_performance.head()

                         engagement_score
                                    count       mean   max
bitId
69a69a9d0a0ce3fd3a6cae83               29  31.855172  70.0
69aac90f4e2d6530993b50a6                1  26.400000  26.4
69b517aff10cd924f53e68b3               24  29.841667  47.6
69b99950d5ba7b8d34df55f8               20  27.170000  43.0
69b99b08d5ba7b8d34df5cb3               28  22.985714  44.6

In [45]:
# CLEAN COLUMN NAMES

reel_performance.columns = [

    "total_views",
    "avg_engagement",
    "max_engagement"

]

reel_performance = reel_performance.reset_index()

reel_performance.head()

                      bitId  total_views  avg_engagement  max_engagement
0  69a69a9d0a0ce3fd3a6cae83           29       31.855172            70.0
1  69aac90f4e2d6530993b50a6            1       26.400000            26.4
2  69b517aff10cd924f53e68b3           24       29.841667            47.6
3  69b99950d5ba7b8d34df55f8           20       27.170000            43.0
4  69b99b08d5ba7b8d34df5cb3           28       22.985714            44.6

In [46]:
# REEL POPULARITY SCORE

reel_performance["reel_popularity_score"] = (

    reel_performance["total_views"] * 0.40 +

    reel_performance["avg_engagement"] * 0.60

)

reel_performance.head()

,bitId,total_views,avg_engagement,max_engagement,reel_popularity_score
0,69a69a9d0a0ce3fd3a6cae83,29,31.855172,70.0,30.713103
1,69aac90f4e2d6530993b50a6,1,26.400000,26.4,16.240000
2,69b517aff10cd924f53e68b3,24,29.841667,47.6,27.505000
3,69b99950d5ba7b8d34df55f8,20,27.170000,43.0,24.302000
4,69b99b08d5ba7b8d34df5cb3,28,22.985714,44.6,24.991429

In [47]:
# TOP TRENDING REELS

reel_performance.sort_values(

    by="reel_popularity_score",

    ascending=False

).head(10)

,bitId,total_views,avg_engagement,max_engagement,reel_popularity_score
48,6a0efe70c5a9d08fea4c67cf,50,30.028000,90.0,38.016800
66,6a1d93cd61d3ca2f147504b8,33,41.218182,95.0,37.930909
49,6a0febf65ecfbb647dcf6c6f,40,33.105000,105.0,35.863000
42,6a0c5c48d4f03db64a78945a,34,35.741176,100.0,35.044706
47,6a0efbb6c5a9d08fea4c6025,40,31.085000,95.0,34.651000
43,6a0c67bed4f03db64a78af0b,39,30.902564,90.0,34.141538
11,69f8fb9568f7e97ef441c429,32,34.650000,100.0,33.590000
46,6a0eee72ed25ae0d7deabbfc,39,29.661538,90.0,33.396923
70,6a1daccb61d3ca2f147522ed,14,46.000000,90.0,33.200000
50,6a101a44a9955ce94394ce5d,42,27.066667,85.0,33.040000

In [48]:
# MERGE POPULARITY FEATURES


bits_df = bits_df.merge(

    reel_performance[
        [
            "bitId",
            "total_views",
            "avg_engagement",
            "reel_popularity_score"
        ]
    ],

    left_on="_id",

    right_on="bitId",

    how="left"

)

print(bits_df.shape)

(87, 30)

# Recommendation Dataset Finalization

In [49]:
# USER FEATURE DATASET

user_features = users_df[

    [
        "_id",
        "username",
        "followerCount",
        "followers_count_actual",
        "following_count_actual",
        "saved_bits_count",
        "saved_products_count",
        "liked_products_count"
    ]

].copy()

user_features.head()

,_id,username,followerCount,followers_count_actual,following_count_actual,saved_bits_count,saved_products_count,liked_products_count
0,698e25132c63bfbc047683d8,krish,2,2,5,2,4,1
1,698e259d2c63bfbc04768479,Pavan,1,1,4,2,2,0
2,698e263e2c63bfbc0476857e,Wamika,0,0,1,1,1,0
3,698e264a2c63bfbc04768582,nishithaa!,2,2,1,1,0,0
4,698e269c2c63bfbc04768709,lucky,0,0,0,0,0,0

In [50]:
# REEL FEATURE DATASET

reel_features = bits_df[

    [
        "_id",
        "title",
        "likeCount",
        "viewCount",
        "shareCount",
        "product_count",
        "avg_engagement",
        "reel_popularity_score"
    ]

].copy()

reel_features.head()

,_id,title,likeCount,viewCount,shareCount,product_count,avg_engagement,reel_popularity_score
0,698e30532c63bfbc04769c5e,Italian pants,2,54,1,1,NaN,NaN
1,698e32a92c63bfbc0476ab3b,Turtleneck shirts,3,78,0,1,NaN,NaN
2,698e33892c63bfbc0476b11f,Leather jacket,3,87,0,1,NaN,NaN
3,69a31d440a0ce3fd3a6bc51f,Accessories u may like,1,52,1,1,NaN,NaN
4,69a330f30a0ce3fd3a6be9b0,Accessories u may like,1,19,0,1,NaN,NaN

In [51]:
# INTERACTION DATASET

print(interaction_df.shape)

interaction_df.head()

(1659, 13)

,_id,userId,bitId,watchPercent,completedWatch,rewatched,replayCount,likedDuringWatch,sharedDuringWatch,addedToCart,watch_score,interaction_score,engagement_score
0,6a08bb67b7bb9861659c3e29,69f8608068f7e97ef44183e4,6a08bb2eb7bb9861659c3e06,0,False,False,0,False,True,False,0.0,15,15.0
1,6a0d9d87d4f03db64a7921bf,6a084ac71a9ba20ae97f5f37,6a0c58c8d4f03db64a788ccd,0,False,False,0,False,True,False,0.0,15,15.0
2,6a0d9d88d4f03db64a7921c4,6a084ac71a9ba20ae97f5f37,6a0c58c8d4f03db64a788ccd,0,False,False,0,False,True,False,0.0,15,15.0
3,6a0ff9a4fac84b0b7fb94d91,698e259d2c63bfbc04768479,6a0efe70c5a9d08fea4c67cf,0,False,False,0,False,False,False,0.0,0,0.0
4,6a0ff9a5fac84b0b7fb94d99,698e259d2c63bfbc04768479,6a0febf65ecfbb647dcf6c6f,0,False,False,0,False,False,False,0.0,0,0.0

In [52]:
print("User Features Shape:")
print(user_features.shape)

print()

print("Reel Features Shape:")
print(reel_features.shape)

print()

print("Interaction Dataset Shape:")
print(interaction_df.shape)

User Features Shape:
(141, 8)

Reel Features Shape:
(87, 8)

Interaction Dataset Shape:
(1659, 13)

# Final Stage of Notebook-1

In [53]:
import os

OUTPUT_PATH = r"E:\zatch-reel-recommendation\data\processed"

os.makedirs(
    OUTPUT_PATH,
    exist_ok=True
)

print("Processed Folder Ready")

Processed Folder Ready

In [54]:
# CLEANED DATASETS

bits_df.to_csv(
    os.path.join(OUTPUT_PATH, "bits_cleaned.csv"),
    index=False
)

products_df.to_csv(
    os.path.join(OUTPUT_PATH, "products_cleaned.csv"),
    index=False
)

users_df.to_csv(
    os.path.join(OUTPUT_PATH, "users_cleaned.csv"),
    index=False
)

reelviews_df.to_csv(
    os.path.join(OUTPUT_PATH, "reelviews_cleaned.csv"),
    index=False
)

print("Cleaned Datasets Saved")

Cleaned Datasets Saved

In [55]:
user_features.to_csv(
    os.path.join(
        OUTPUT_PATH,
        "user_features.csv"
    ),
    index=False
)

reel_features.to_csv(
    os.path.join(
        OUTPUT_PATH,
        "reel_features.csv"
    ),
    index=False
)

interaction_df.to_csv(
    os.path.join(
        OUTPUT_PATH,
        "interaction_dataset.csv"
    ),
    index=False
)

print("Feature Datasets Saved")

Feature Datasets Saved

In [56]:
os.listdir(OUTPUT_PATH)

['bits_cleaned.csv',
 'interaction_dataset.csv',
 'products_cleaned.csv',
 'reelviews_cleaned.csv',
 'reel_features.csv',
 'users_cleaned.csv',
 'user_features.csv']

# Final Notebook Summary

In [57]:
print("="*60)
print("DATA PREPROCESSING COMPLETED")
print("="*60)

print()

print("Users:", users_df.shape)
print("Bits:", bits_df.shape)
print("Products:", products_df.shape)
print("ReelViews:", reelviews_df.shape)

print()

print("User Features:", user_features.shape)
print("Reel Features:", reel_features.shape)
print("Interaction Dataset:", interaction_df.shape)

print()

print("Ready For Notebook 02")

============================================================
DATA PREPROCESSING COMPLETED
============================================================

Users: (141, 39)
Bits: (87, 30)
Products: (106, 38)
ReelViews: (1659, 26)

User Features: (141, 8)
Reel Features: (87, 8)
Interaction Dataset: (1659, 13)

Ready For Notebook 02